---
kind: pipeline
name: discovery-service-pipeline

steps:
  - name: "notify start"
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook_discovery-service
      channel: discovery-service
      template: >
        Build {{build.number}} started at {{build.started}}. View it at {{build.link}}
  - name: "unit, build, package, publish"
    image: davidiamyou/open-jdk-8:latest
    commands:
      - ./gradlew test
      - ./gradlew build
      - ./gradlew shadowJar
      - printf "latest," > .tags
      - ./gradlew properties -q | grep "version:" | awk '{print $2}' | cat >> .tags
  - name: "docker"
    image: plugins/docker
    settings:
      repo: registry.imulab.io/astrea/discovery-service
      registry: registry.imulab.io
      insecure: true
  - name: "notify"
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook_discovery-service
      channel: discovery-service
      template: >
        {{#success build.status}}
          Build {{build.number}} succeeded!
        {{else}}
          Build {{build.number}} failed! Please fix me at {{build.link}}!
        {{/success}}