/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package io.imulab.astrea.service.discovery

import com.fasterxml.jackson.databind.module.SimpleModule
import com.fasterxml.jackson.module.kotlin.registerKotlinModule
import com.typesafe.config.Config
import com.typesafe.config.ConfigFactory
import io.imulab.astrea.sdk.oidc.discovery.Discovery
import io.vertx.core.Vertx
import io.vertx.core.VertxOptions
import io.vertx.core.json.Json
import io.vertx.ext.healthchecks.HealthCheckHandler
import org.slf4j.LoggerFactory
import java.nio.charset.StandardCharsets

private val logger = LoggerFactory.getLogger("io.imulab.astrea.service.discovery.AppKt")

fun main(args: Array<String>) {
    val vertx = Vertx.vertx(VertxOptions().apply {
        preferNativeTransport = true
    })

    Json.mapper.registerKotlinModule()
    Json.prettyMapper.registerKotlinModule()

    val config = ConfigFactory.load()
    val discovery = readDiscovery(vertx, config)
    val healthCheckHandler = HealthCheckHandler.create(vertx)

    vertx.deployVerticle(DiscoveryHttpApi(discovery, config, healthCheckHandler)) { ar ->
        if (ar.failed()) {
            logger.error("Server encountered error.", ar.cause())
        } else {
            logger.info("Discovery HTTP API deployed with id {}", ar.result())
        }
    }

    vertx.deployVerticle(DiscoveryGrpcApi(discovery, config, healthCheckHandler)) { ar ->
        if (ar.failed()) {
            logger.error("Server encountered error.", ar.cause())
        } else {
            logger.info("Discovery gRPC API deployed with id {}", ar.result())
        }
    }
}

private fun readDiscovery(vertx: Vertx, config: Config): Discovery {
    val source = if (config.hasPath("discovery.source")) config.getString("discovery.source") else ""
    if (!source.isNullOrEmpty()) {
        return Json.decodeValue(vertx.fileSystem().readFileBlocking(source), DiscoveryJson::class.java)
    }

    val json = Service.javaClass.classLoader.getResourceAsStream(config.getString("discovery.default"))
        .reader(StandardCharsets.UTF_8)
        .readText()
    return Json.decodeValue(json, DiscoveryJson::class.java)
}

private object Service